apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/Emc285/argocd-ext-values.git
        revision: HEAD
        files:
          - path: "configs/tst/values.yaml"
  template:
    metadata:
      name: test
    spec:
      project: default
      source:
        path: demo
        repoURL: https://github.com/Emc285/argocd-ext-values.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - valuesxyz.yaml
            - values-tst.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: tst