---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-teste
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tst
  project: default
  source:
    path: demo
    plugin:
      env:
        - name:  REPO_NAME
          value: "traefik"
        - name:  REPO_URL
          value: "<https://helm.traefik.io/traefik>"
        - name:  CHART_NAME
          value: "traefik"
        - name:  CHART_VERSION
          value: "10.6.2"
        - name:  COMMAND
          value: "--values traefik-values.yaml"
      name: helm-resolver
    repoURL: https://github.com/Emc285/argocd-ext-values.git