apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/Emc285/JT-values-argocd.git
        revision: HEAD
        files:
          - path: configs/tst
  template:
    metadata:
      name: test
    spec:
      project: default
      source:
        helm:
          parameters:
#          valueFiles:
#            - values.yaml
            - '{{path.filename}}'
          values: |-
            {{values}}
        path: demo
        repoURL: https://github.com/Emc285/argocd-ext-values.git
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: tst