apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Emc285/argocd-ext-values.git
    targetRevision: HEAD
    path: demo
  destination:
    server: https://kubernetes.default.svc
    namespace: tst