apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/Emc285/JT-values-argocd.git
        revision: HEAD
        directories:
          - path: configs/tst/*
  template:
    metadata:
      name: test
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - values.yaml
          values: |-
            'banana'
        path: demo
        repoURL: https://github.com/Emc285/argocd-ext-values.git
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: tst