---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-private-values
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tst
  project: default
  source:
    path: demo
    plugin:
      env:
        - name:  REPO_NAME
          value: "teste"
        - name:  REPO_URL
          value: "<https://helm.traefik.io/traefik>"
        - name:  CHART_NAME
          value: "app"
        - name:  CHART_VERSION
          value: "0.1.0"
        - name:  COMMAND
          value: "--values values.yaml"
      name: helm-resolver
    repoURL: https://github.com/Emc285/argocd-ext-values.git