---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-teste
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tst
  project: default
  source:
    path: demo
    plugin:
      env:
        - name:  REPO_NAME
          value: "test-emc"
        - name:  REPO_URL
          value: "https://emc285.github.io/helm-chart/"
        - name:  CHART_NAME
          value: "helm-chart-test"
        - name:  CHART_VERSION
          value: "0.1.0"
        - name:  COMMAND
          value: "--values values.yaml"
      name: helm-resolver
    repoURL: https://github.com/Emc285/argocd-ext-values.git