apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
spec:
  generators:
    - git:
        repoURL: https://github.com/Emc285/argocd-ext-values.git
        revision: HEAD
      files:
        - path: "demo/**.yaml"
  template:
    metadata:
      name: 'example'
    spec:
      project: default
      source:
#        helm:
#          valueFiles:
#            - values.yaml
#          values: |-
##            {{values}}
#          values: |
#            values.yaml
        repoURL: https://github.com/Emc285/argocd-ext-values.git
        targetRevision: HEAD
        path: demo
      destination:
        server: https://kubernetes.default.svc
        namespace: tst