namespaces:
  - prd
  - cq
  - tst

name: app

nameOverride: testecenas

replicaCount: 3

service:
  type: NodePort
  port: 30008

image:
  repository: amralaayassen/helm-app
  pullPolicy: IfNotPresent